global:
  postgresql:
    auth:
      postgresPassword: "a0dev"
      username: "a0"
      password: "a0dev"
      database: "agentzero"

postgresql:
  replicaCount: 3
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  persistence:
    enabled: true
    storageClass: "fast-ssd"
    size: "10Gi"

pgpool:
  replicaCount: 2
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

persistence:
  enabled: true
  storageClass: "fast-ssd"
  size: "10Gi"

metrics:
  enabled: true
