
services:
  # Neo4j Graph Database - FIXED VERSION
  neo4j:
    image: neo4j:5.11-community
    container_name: agent-zero-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt Protocol
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/agent_zero_neo4j_dev
      
      # Memory settings for development
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 512m
      
      # Network settings
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
      NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
      
      # APOC procedures (if needed)
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      
      # Transaction timeout
      NEO4J_dbms_transaction_timeout: 60s
    volumes:
      - ./data/neo4j:/data
      - ./logs/neo4j:/logs
      - ./import:/import
      - ./plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  # PostgreSQL Database (if needed)
  postgres:
    image: postgres:15-alpine
    container_name: agent-zero-postgres
    environment:
      POSTGRES_DB: agent_zero
      POSTGRES_USER: agent_zero
      POSTGRES_PASSWORD: agent_zero_dev_password
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_zero -d agent_zero"]
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ Message Broker (if needed)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: agent-zero-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: agent_zero
      RABBITMQ_DEFAULT_PASS: agent_zero_rabbit_dev
      RABBITMQ_DEFAULT_VHOST: agent_zero_vhost
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  neo4j_data:
    driver: local
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  default:
    name: agent-zero-network
