version: '3.8'

services:
  neo4j:
    image: neo4j:5.14-community
    container_name: agent-zero-neo4j
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/agent-zero-password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./shared/knowledge/schema.cypher:/import/schema.cypher
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
