services:
  neo4j:
    image: neo4j:5.15-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_heap_initial__size=512m
    networks:
      - agent-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.ai-intelligence
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
