global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'agent-zero-v2'
    static_configs:
      - targets: 
          - 'api-gateway:8080'
          - 'ai-intelligence:8010'
          - 'websocket-service:8080'
          - 'agent-orchestrator:8080'
    scrape_interval: 10s

  - job_name: 'infrastructure'
    static_configs:
      - targets:
          - 'neo4j:7474'
          - 'redis:6379'
