apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: a0-dev

resources:
  - storage-class.yaml
  - configmap.yaml
  - secrets.yaml

commonLabels:
  app.kubernetes.io/name: agent-zero
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
  environment: development
