[project]
name = "agent-zero-cli"
version = "1.0.0"
description = "Agent Zero Command Line Interface"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.9.0",
    "rich>=13.7.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "tabulate>=0.9.0",
]

[project.scripts]
a0 = "a0:app"
