apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-orchestrator
  namespace: a0-dev
  labels:
    app: agent-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-orchestrator
  template:
    metadata:
      labels:
        app: agent-orchestrator
    spec:
      serviceAccountName: agent-zero-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: agent-orchestrator
        image: agent-zero/agent-orchestrator:1.0.0
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: LOG_LEVEL
        - name: AI_ROUTER_URL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: AI_ROUTER_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: agent-orchestrator-service
  namespace: a0-dev
  labels:
    app: agent-orchestrator
spec:
  selector:
    app: agent-orchestrator
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  type: ClusterIP
