apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-router
  namespace: a0-dev
  labels:
    app: ai-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-router
  template:
    metadata:
      labels:
        app: ai-router
    spec:
      serviceAccountName: agent-zero-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: ai-router
        image: agent-zero/ai-router:1.0.0
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: LOG_LEVEL
        - name: OLLAMA_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: OLLAMA_BASE_URL
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: a0-secrets
              key: ANTHROPIC_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: a0-secrets
              key: OPENAI_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-router-service
  namespace: a0-dev
  labels:
    app: ai-router
spec:
  selector:
    app: ai-router
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
