apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: a0-dev
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: agent-zero-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: api-gateway
        image: agent-zero/api-gateway:1.0.0
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: LOG_LEVEL
        - name: AI_ROUTER_URL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: AI_ROUTER_URL
        - name: CHAT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: CHAT_SERVICE_URL
        - name: AGENT_ORCHESTRATOR_URL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: AGENT_ORCHESTRATOR_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: a0-dev
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
