apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-storage
  namespace: a0-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-service
  namespace: a0-dev
  labels:
    app: docs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-service
  template:
    metadata:
      labels:
        app: docs-service
    spec:
      serviceAccountName: agent-zero-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: docs-service
        image: agent-zero/docs-service:1.0.0
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: a0-config
              key: LOG_LEVEL
        volumeMounts:
        - name: docs-storage
          mountPath: /app/docs
        - name: source-code
          mountPath: /app/source
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: docs-storage
        persistentVolumeClaim:
          claimName: docs-storage
      - name: source-code
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: docs-service
  namespace: a0-dev
  labels:
    app: docs-service
spec:
  selector:
    app: docs-service
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http
  type: ClusterIP
